name: Nuxt Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate static site
        run: npm run generate

      - name: Check Nuxt output
        run: ls -R .output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-dist
          path: .output/public  # upload the folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuxt-dist
          path: app_backup

      - name: Check files before SCP
        run: ls -R app_backup

      - name: Upload new build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "app_backup/*"
          target: /home/mtech-marketing/app_backup

  move_file:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Move build on VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            rm -rf old_app
            cp -r app old_app
            rm -rf app
            cp -r app_backup/* app/
            rm -rf app_backup

